<?php

use AnalyticsCard\Classes\APIHandler;

class APIHandlerTest extends PHPUnit_Framework_TestCase
{

    private $hero = null;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    function test_prepare_service()
    {

        $handler = new APIHandler(getenv('ACCESS_FILE_P12'), getenv('SERVICE_EMAIL'));

        try {
            $service = $handler->getService();
            $view = $handler->getFirstprofileId(getenv('TRACKING_ID'));
        } catch (\Exception $e) {
            $this->fail("Service creation failed: " . $e->getMessage());
        }

    }

    function test_wrong_tracking_id()
    {
        $handler = new APIHandler(getenv('ACCESS_FILE_P12'), getenv('SERVICE_EMAIL'));
        $bad_tracking_id = "UA-59699402-4";

        $this->setExpectedException("Exception",'No accounts found with TRACKING ID: '.$bad_tracking_id);

        $service = $handler->getService();
        $view = $handler->getFirstprofileId($bad_tracking_id);

    }

    function test_request_data()
    {
        $handler = new APIHandler(getenv('ACCESS_FILE_P12'), getenv('SERVICE_EMAIL'));

        try {
            $service = $handler->getService();
            $view = $handler->getFirstprofileId(getenv('TRACKING_ID'));

            $results = $service->data_ga->get(
                'ga:' . $view,
                '120daysAgo',
                'today',
                'ga:avgTimeOnPage,ga:users',
                [
                    "dimensions" => "ga:country,ga:city,ga:pagePath",
                ]
            );

            // just be sure that data was returned
            $this->assertNotEquals(0, count($results->getRows()));

            // make sure that data array have right order of fields
            $rows = $results->getRows();
            $row = $rows[0];
            $this->assertEquals(5,count($row));


        } catch (\Exception $e) {
            $this->fail("Service creation failed: " . $e->getMessage());
        }
    }

}