<?php

use AnalyticsCard\Classes\Row;

class RowTest extends PHPUnit_Framework_TestCase
{
    private $row;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->row = new Row();
    }


    function test_getters_and_setters() {

        $title = "Some1";
        $users = 12;
        $avgTime = 44.22;

        $this->row->setTitle($title);
        $this->row->setUsers($users);
        $this->row->setAvgTimeOnPage($avgTime);

        $this->assertEquals($title, $this->row->getTitle());
        $this->assertEquals($users, $this->row->getUsers());
        $this->assertEquals($avgTime, $this->row->getAvgTimeOnPage(true));

    }
}